add_cpm_module(framegraph)

add_library(framegraph_framework_cpm STATIC IMPORTED)
set_target_properties(framegraph_framework_cpm PROPERTIES IMPORTED_LOCATION ${framegraph_ROOT}/lib/Framework.lib)

add_library(framegraph_vulkanloader_cpm STATIC IMPORTED)
set_target_properties(framegraph_vulkanloader_cpm PROPERTIES IMPORTED_LOCATION ${framegraph_ROOT}/lib/VulkanLoader.lib)

add_library(framegraph_stl_cpm STATIC IMPORTED)
set_target_properties(framegraph_stl_cpm PROPERTIES IMPORTED_LOCATION ${framegraph_ROOT}/lib/STL.lib)

add_library(framegraph_pipelinecompiler_cpm STATIC IMPORTED)
set_target_properties(framegraph_pipelinecompiler_cpm PROPERTIES IMPORTED_LOCATION ${framegraph_ROOT}/lib/PipelineCompiler.lib)

add_library(framegraph_cpm STATIC IMPORTED)
set_target_properties(framegraph_cpm PROPERTIES IMPORTED_LOCATION ${framegraph_ROOT}/lib/FrameGraph.lib)
target_include_directories(framegraph_cpm INTERFACE ${framegraph_ROOT}/include)
target_include_directories(framegraph_cpm INTERFACE ${framegraph_ROOT}/include/vulkan_loader/1.1)
target_compile_definitions(framegraph_cpm INTERFACE FG_ENABLE_VULKAN=1 FG_ENABLE_VULKAN_MEMORY_ALLOCATOR=1 COMPILER_MSVC=1 FG_STD_VARIANT=1 FG_STD_OPTIONAL=1 FG_STD_STRINGVIEW=1 FG_CACHE_LINE=std::hardware_destructive_interference_size FG_HAS_HASHFN_HashArrayRepresentation=1 FG_HAS_HASHFN_HashBytes=1 FG_HAS_HASHFN_Murmur2OrCityhash=1 FG_VULKAN_TARGET_VERSION="110")
target_link_libraries(framegraph_cpm INTERFACE framegraph_framework_cpm framegraph_vulkanloader_cpm framegraph_stl_cpm framegraph_pipelinecompiler_cpm)
